### ISSUE TITLE
Load historic data giving unique constraint violated: Table(DB_COMMERCIALMEASURES)

### ISSUE THREAD

**Issue by rvr2020** [SAP-samples/btp-resource-consumption-monitor#15]
Thanks for contributing to this project. I followed the instructions and successfully set up all apps running. However, I get a unique constraint error when I try to do a historical load.

<img width="1254" alt="image" src="https://github.com/SAP-samples/btp-resource-consumption-monitor/assets/5060854/34f5f35f-172b-4edd-b7b6-aa88722f8e05">

<img width="2436" alt="image" src="https://github.com/SAP-samples/btp-resource-consumption-monitor/assets/5060854/6d0580d4-6f8e-4f2b-8f77-cf2d5ab365b6">

**Comment by willemi069808** [comment]
Hi @rvr2020 ,
Thank you for reaching out. This shouldn't happen, but to explore the cause, I'd like to know the following:
- Is this a new installation or did you try to 'upgrade' from a version 1.x deployment? (this is not supported)
- Do you have more than 1 global account connected (default is 1)
- Is this a pure BTPEA/CPEA account, or is it a mixed Subscription/Consumption global account?

You can reach me on teams or via email to resolve as well (willem.pardaens-at-sap.com)

**Comment by willemi069808** [comment]
After investigation the issue was due to a change in naming from SAP side where the name "PostgreSQL, hyperscaler option" changed over time to "PostgreSQL, Hyperscaler Option" (with capitals) and instances with both naming versions were active in the account. A fix will be published. Thank you for your feedback.
