### ISSUE TITLE
Application logging service Consumption charge

### ISSUE THREAD

**Issue by Gagan-Zoetis** [SAP-samples/btp-resource-consumption-monitor#16]
Hello Team,

After implementing the application log service, we noticed that we are getting heavily charged for Application Log monitoring service on daily basis and for monthly basis it will be in thousands USD. Can we configure the BTP resource consumption monitoring without application log monitoring service and how we can reduce the billing?

Regards
Gagan

**Comment by willemi069808** [comment]
Hi Gagan,

The application logging service is an optional service you can choose to disable if you like. However, the charges you are referring to is probably just an inflated Forecast due to a missing Forecast Configuration for this service (see: https://github.com/SAP-samples/btp-resource-consumption-monitor?tab=readme-ov-file#forecasting-configuration).

The Application Logging Service in standard plan would roughly be charged at 260 euros per month. (see here: https://www.sap.com/products/technology-platform/price-list/list.cpea.europe.html). Not per day.

Given that the usage of this service is rather stable in time, you can configure the Forecast Configuration for this line as 'Excluded'.

Opening the tool on a 1st of the month can always be a bit scary as it will multiply all your service charges by 31 if the Forecast Configuration has not been changed from the default.

**Comment by Gagan-Zoetis** [comment]
Thank you, Willem, for your quick response. I am able to update "exclude" for forecast configuration.
