### ISSUE TITLE
Plan Details are wrong

### ISSUE THREAD

**Issue by brahammittal** [SAP-samples/btp-resource-consumption-monitor#18]
Hi Team,

The plan details shown on the service are wrong, we are using standard plan but the app shows default plan.

**Comment by willemi069808** [comment]
Hi,

Can you please elaborate on the issue? Which BTP service are you referring to? How does it show in the BTP Cockpit and how does it show in the tool?

**Comment by willemi069808** [comment]
Hi,

I noticed the same in our environment for the DQM service: the cockpit shows 'standard' whereas the application shows 'default'. This is due to the different solutions in which we maintain our product hierarchy, taxonomy and commercialization plans, where the 'technical' and 'external' names are defined and referenced. Even though it's a bit confusing, the 'standard' and 'default' denote the same offering here in this case. You can validate this by looking at the 'Usage Analytics' in the BTP cockpit for this service which will show 'default' as well.
