### ISSUE TITLE
Cannot create connection from SAC to HANA DB

### ISSUE THREAD

**Issue by nikolicm55** [SAP-samples/btp-resource-consumption-monitor#21]
Hi Willem,

I have followed GitHub and video instructions to setup Consumption monitor application and all worked well untill SAC to HANA DB connection. Upon entring all required connection details and clicking on OK, below error is returned:
"We couldn't connect to your HANA system. Possible causes: The SSL certificate is not trusted, or a network error occurred. For more information, see our troubleshooting page. Correlation ID: 30077726-9512-4628-b045-824220170884"
I did check Cloud HANA instance Connection setup and it is set to "Allow specific IP addresses and IP ranges (in addition to Cloud Foundry in BTP)". My understanding is that this configuration should allow SAC tenant connection (ap10 - AWS AU) and IP range should be already covered. 
Usage Data service is enabled in a dedicated subaccount while HANA DB is in separated subaccount and we used instance mapping.
Also, I have tried to test btprc db connection using browser and  host:port from the db key but I've got host unreachable message.
Can you please advise.

Best Regards,
Mario Nikolic

**Comment by willemi069808** [comment]
Hi Mario,

Your assumptions are correct. But note that the default BTP Cloud Foundry IP allowlisting only applies to same-region connectivity. You mentioned ap10 for SAC, is that the same region as where you deployed the application?

Browser access will not work, because this will use your laptop outbound IP which is not part of the BTP range. For this to work you will have to add your IP address to the list, or temporarily set it to 'allow all IP addresses'.

Lastly, make sure that you take the correct user/password details from the service key, as it is easy to mistakenly copy the di_user/hdi_password instead.

Let me know, before we dive a bit deeper.

**Comment by nikolicm55** [comment]
Hi Willem,

Thank you for the quick response. Just to clarify that I've correclty understood BTP IP rules, if both instances are in the same region, default rules will work but not across different regions. For an example our HANA Cloud instance is in ap20 and I have created new FinOps subaccount also in ap20 so I don't need additional HANA DB instances (cost related). However, our SAC tenants are provisioned independently and there in ap10 region. So if I am correct, to allow live connection I will need to add ap10 region IP ranges into out HANA DN (ap10) IP allowed list.

Regards,
Mario

**Comment by willemi069808** [comment]
Yes, that is correct. Because you are using 2 different regions, it is not covered by the default rules and you have to add the SAC ap10 egress range manually.

**Comment by nikolicm55** [comment]
Thank you
