### ISSUE TITLE
App not working as expected

### ISSUE THREAD

**Issue by NAVK76** [SAP-samples/btp-resource-consumption-monitor#33]
Hi Team,

1) we tried to deploy this app with Free HANA cloud DB and remining entitlement with standard plan and CF app deployed successfully without any issue.

2) as next step we created HANA cloud live connection to above HANA DB as pre the credentials from btprc-db key and that also successful and we upload the content and imported the same and then we did Trusted Origins also and then pointed all the modeler also to the new destination we setup above. but now when we try to open the stories its empty and no data is loading here.
Below is the screenshot for Technical allocation
<img width="957" alt="image" src="https://github.com/user-attachments/assets/5f88ddb6-0253-49e3-8273-4f51f30e2504">

Below for CrossChargingDaily:
<img width="959" alt="image" src="https://github.com/user-attachments/assets/d3cd7d03-6beb-4f35-80bb-a39a23bcb92b">
Below for CrossChargingMonthly:
<img width="960" alt="image" src="https://github.com/user-attachments/assets/af0b64f5-bced-4cb6-b464-40d761a5b45e">

only CreditsProjection only working fine and showing us the data.

**With this issue we moved and also deployed site in workzone and assigned the roles and later when we open the same we are getting no information, please find the below screenshot.

Note: Here in workzone also only credit consumption and  only giving as the data and remining all empty only** 
**Actual issue:**
<img width="960" alt="image" src="https://github.com/user-attachments/assets/b2addd3f-3547-4ffb-b59f-a1fbc60703d5">

Can you please help us with this issue.
Thanks in advance.

**Comment by willemi069808** [comment]
Hi Naveen,

Regarding the first part, that is perfectly normal: Technical Allocation will only show data when you are using that feature (you need to configure it). Cross charging will only show data when you tag items (you need to configure it). Also, 'daily' readings are only available for those days when the tool was already deployed. One of your screenshots is from 'july 1st' so you won't have data for that day. You can access all 4 SAC reports from within the Work Zone screens.

For the second part: this is because there isn't any data for the tool to display. There is currently an issue (see #24) which causes no data to be available from the central metering API during the first few days of a new month. I can see data is coming in now for November, so today you should see data.

Hope this helps.
